### ISSUE TITLE
Establish and test connection with charger

### ISSUE THREAD

**Issue by ljungqvistaxel** [AlexTelon/FlexiCharge-BMS#103]
To be able to seamlessly charge the battery, the charger and BMS need to communicate according to specification document. This meaning that every message type is tested for functionality with both systems connected.

Requirements
- Every message type that can be sent over the UART wires should be tested together with the charger connected.
- A full charging session (from chargers perspective) should be able to take place without human interaction in the BMS

**Comment by ljungqvistaxel** [comment]
Effort: 5

**Comment by KevFord** [comment]
The software has been tested with both squad's hardware and it is working as intended. Software is currently awaiting review.

**Comment by KevFord** [comment]
Closed with the completion of task #98 and #103.
