### ISSUE TITLE
#103 meeting with charger ( 1 dev + testlead

### ISSUE THREAD

**Issue by ecle20yy** [AlexTelon/FlexiCharge-BMS#104]
#103 One dev, preferably the person who implemented communication, from each squad and the test lead from each squad. 
Setup meeting and ensure communication between hardwares work.

**Comment by KevFord** [comment]
Meeting booked.

**Comment by KevFord** [comment]
Hardware test successfull. The software was modified during this meeting and is now awaiting review on github.

**Comment by KevFord** [comment]
Closed along with task #98.
