### ISSUE TITLE
Read battery cell voltage

### ISSUE THREAD

**Issue by ljungqvistaxel** [AlexTelon/FlexiCharge-BMS#25]
To be able to monitor the voltage of a battery, software and a circuit for reading the voltage of a single battery cell should first be developed. The full range of possible voltages for the battery cell should be readable.

This is working towards issue #15 

Effort: 8

**Comment by KevFord** [comment]
The software is implemented and awaiting review on github. the circuit is available on github.

**Comment by KevFord** [comment]
All software related to this task is now done and uploaded to github. Awaiting completion of task #34 and #36.

**Comment by davidtey** [comment]
This item is now complete with the completion of #36.
