### ISSUE TITLE
Implement communication protocol

### ISSUE THREAD

**Issue by ljungqvistaxel** [AlexTelon/FlexiCharge-BMS#28]
A communication between the charger and the BMS is needed to monitor and control charging of a battery. Establish communication as agreed with charger squad and exchange some information. The communication can be tested without the actual charger connected.

This is working towards #18

**Comment by ljungqvistaxel** [comment]
Effort: 8

**Comment by KevFord** [comment]
All software is done and tested, awaiting review.

**Comment by ljungqvistaxel** [comment]
New estimated effort: 1

**Comment by KevFord** [comment]
Closed with the completion of task #98.
