### ISSUE TITLE
Decide MCU

### ISSUE THREAD

**Issue by ViktorM02** [AlexTelon/FlexiCharge-BMS#29]
### Parent Backlog Item

#23

### Description of new task

Researching MCU, create meeting and vote

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

**Comment by ViktorM02** [comment]
An STM32 was decided as the MCU for the bms :)

**Comment by ecle20yy** [comment]
If this is done, then ***Close with Comment***!!!
