### ISSUE TITLE
Install STM32CubeIDE

### ISSUE THREAD

**Issue by ViktorM02** [AlexTelon/FlexiCharge-BMS#31]
### Parent Backlog Item

#23

### Description of new task

Since the STM32 was decided for the projects mcu, all developers and testers need to install the work environment  (STM32CubeIDE)

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

**Comment by davidtey** [comment]
Devs have all installed IDE
