### ISSUE TITLE
Wire circuit

### ISSUE THREAD

**Issue by ViktorM02** [AlexTelon/FlexiCharge-BMS#34]
### Parent Backlog Item

#25

### Description of new task

After a design of the circut for reading a cells voltage on the mcu, it should be wired and connected to the STM32.

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

**Comment by hofr19ea** [comment]
closed as done
