### ISSUE TITLE
Implement reading individual cells voltage

### ISSUE THREAD

**Issue by ViktorM02** [AlexTelon/FlexiCharge-BMS#35]
### Parent Backlog Item

#25

### Description of new task

Configure the ADC and implement! This code should later be pushed to the repo.

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

**Comment by KevFord** [comment]
This task is connected to task #53, which I just created a pull request for.

**Comment by KevFord** [comment]
Completed in association with task #53
