### ISSUE TITLE
Confirm/test voltage reading range

### ISSUE THREAD

**Issue by ViktorM02** [AlexTelon/FlexiCharge-BMS#36]
### Parent Backlog Item

#25

### Description of new task

Make sure the MCU reads the comlete voltage range of the cell (0v to 3.7v. Maybe higher?). A multimeter or osilloscope are tools that could be used for this.

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

**Comment by davidtey** [comment]
test passed
