### ISSUE TITLE
Set up documentation for software

### ISSUE THREAD

**Issue by ljungqvistaxel** [AlexTelon/FlexiCharge-BMS#40]
For future developers to easily take over the development, a document describing how the software works should be created and updated when more work is done. Preferable a markdown file, to work well with git and GitHub.

**Comment by ljungqvistaxel** [comment]
Renamed after feedback during backlog grooming

**Comment by KevFord** [comment]
Completed by closing task #57. A basic document with some structure and rules on how to add to it is now available on github.
