### ISSUE TITLE
Measure current

### ISSUE THREAD

**Issue by ljungqvistaxel** [AlexTelon/FlexiCharge-BMS#47]
To determine the suitable charging stage for a cell and detect overcharging, the flow of current during charging should be measured. The current span of charging a battery should be supported.

This is working towards #16 

Effort: 5

**Comment by ViktorM02** [comment]
The reading at higher current becomes the less accurate the implementation becomes, since the resistors gets hot, which leads to change of the resistance. The resistors will need to be changed in the future to power resistors instead of regular ones.
