### ISSUE TITLE
Research cell charging

### ISSUE THREAD

**Issue by ljungqvistaxel** [AlexTelon/FlexiCharge-BMS#52]
To be able to create a charging circuit, research on how charging should be done should be done. To be done with this backlog item, the squad should know how a battery should be charged safely from start to finish.

**Comment by ljungqvistaxel** [comment]
Effort: 5

**Comment by KevFord** [comment]
I am currently reading up on how charging of Li-ion batteries are typically done.

**Comment by ljungqvistaxel** [comment]
Effort left: 2
