### ISSUE TITLE
[Task]: Upload code to git

### ISSUE THREAD

**Issue by ecle20yy** [AlexTelon/FlexiCharge-BMS#53]
### Parent Backlog Item

#25

### Description of new task

The code shall be uploaded to git.

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

**Comment by KevFord** [comment]
Created a pull request and currently awaiting review. This task is connected to task #35

**Comment by KevFord** [comment]
Closed together with task #35
