### ISSUE TITLE
[Task]: Setup start project to git

### ISSUE THREAD

**Issue by ecle20yy** [AlexTelon/FlexiCharge-BMS#54]
### Parent Backlog Item

#51

### Description of new task

A blank cubeMX project shall be uploaded to git to allow others to work from.

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

**Comment by ljungqvistaxel** [comment]
closed because merged into dev
