### ISSUE TITLE
[Task]: Create base document

### ISSUE THREAD

**Issue by ecle20yy** [AlexTelon/FlexiCharge-BMS#57]
### Parent Backlog Item

#40

### Description of new task

Near blank doc woth some minor structure to allow other devs to work on it

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

**Comment by KevFord** [comment]
Begun writing a basic document for how software will be documented

**Comment by KevFord** [comment]
Completed after dealing with a blocked pull request due to some markdown syntax errors.
