### ISSUE TITLE
[Task]: Create base electrical diagram and push to git

### ISSUE THREAD

**Issue by ecle20yy** [AlexTelon/FlexiCharge-BMS#58]
### Parent Backlog Item

#27

### Description of new task

This will allow other devs to work on this. Can contain minor frameworks

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

**Comment by ViktorM02** [comment]
The base diagram is in bms_hardware.
