### ISSUE TITLE
[Task]: Implement voltage reading electrical diagram

### ISSUE THREAD

**Issue by ecle20yy** [AlexTelon/FlexiCharge-BMS#59]
### Parent Backlog Item

#27

### Description of new task

This sould be added to the base file created by #58 

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

**Comment by ViktorM02** [comment]
Lays in the bms_hardware, the file "battery_management_system.asc"
