### ISSUE TITLE
[Task]: Choose method to create electrical diagram

### ISSUE THREAD

**Issue by ecle20yy** [AlexTelon/FlexiCharge-BMS#60]
### Parent Backlog Item

#27

### Description of new task

This should be a framework that works well with GIT

### Required Manual Steps

- [X] Confirm title is filled out
- [X] Additional labels added.
- [X] Confirm parent backlog item has correct issue id

**Comment by ViktorM02** [comment]
There desn't seem to be any good options with diagrams on git... :(

**Comment by ViktorM02** [comment]
LtSpice was decided, since its free, capable and the file size is tiny. :) Was discussed and approved by @ljungqvistaxel
