### ISSUE TITLE
#28: Implement UART communication

### ISSUE THREAD

**Issue by ViktorM02** [AlexTelon/FlexiCharge-BMS#98]
Implement UART based on communication protocol. The implementation should take consideration of the timeout limit with no connection.

**Comment by KevFord** [comment]
The software now works using mock data. Working on documentation.

**Comment by KevFord** [comment]
Software is done and tested with the Charger's hardware. Awaiting review.

**Comment by KevFord** [comment]
All the software is now available in dev.
